### ISSUE TITLE
Opcode 0xC4 weirdness

### ISSUE THREAD

**Issue by raddad772** [adtennant/sm83-test-data#4]
0xC4 has a null cycle in between regular cycles. I'm not sure how to interpret this as opcode tables say it should have 12 or 24 (so 3 or 6) cycles to it, and there's a different number of cycles than that.
Furthermore, the cycles after the null no longer use hex strings, but instead, bare numbers.

**Comment by raddad772** [comment]
same issue in 0xC5

**Comment by raddad772** [comment]
0xC7 too

**Comment by raddad772** [comment]
0xCA

**Comment by raddad772** [comment]
0xCC

**Comment by raddad772** [comment]
0xCD

**Comment by raddad772** [comment]
0xD4

**Comment by raddad772** [comment]
0xD5, 0xD7, 0xDC, 0xDF, 0xE5

**Comment by raddad772** [comment]
0xE7, 0xEF, 0xF5, 0xF7
that seems to be all?

**Comment by adtennant** [comment]
I'm not sure I understand the issue with 0xC4. Every test has 3 or 6 entries in the `cycles` array, the `null` entries are cycles where there is no bus activity, i.e. no reads or writes.
