### ISSUE TITLE
0xCB should have individual instructions

### ISSUE THREAD

**Issue by raddad772** [adtennant/sm83-test-data#6]
Hi, it's kind of a pain to use the tests this way if they don't work.

If you check out my Z80 tests, you can see how I handle this:
https://github.com/raddad772/jsmoo/tree/main/misc/tests/GeneratedTests/z80/v1

CB 04

becomes

cb 04.json

It even works for longer opcodes the SM83 doesn't have to deal with that have operands in the stream, like

dd cb __ 17.json

**Comment by adtennant** [comment]
Fixed in https://github.com/adtennant/SharpLR35902Tests/tree/master/v2, the 0xCB instruction now contains 1,000 tests per individual instruction.
