### ISSUE TITLE
Missing null cycles?

### ISSUE THREAD

**Issue by ronnodas** [adtennant/sm83-test-data#7]
What is the cycle entry in each test supposed to be exactly? For example, all other sources about timings I can find say the opcode `0x18` should take 3 m-cycles (from the details on https://izik1.github.io/gbops/index.html I expect it to be two reads followed by a null), but each test in `18.json` only lists 2 cycles. Am I misunderstanding something? I'm seeing similar mismatches for each of the opcodes `09, 18, 19, 20, 28, 29, 30, 38, 39, c0, c2, c3, c8, c9, ca, d0, d2, d8, d9, da, e8, f8`, some of them only in the case where the branch *is* taken.

**Comment by adtennant** [comment]
Fixed in https://github.com/adtennant/SharpLR35902Tests/tree/master/v2
