### ISSUE TITLE
Potential issue with 0x04 tests

### ISSUE THREAD

**Issue by Hucaru** [adtennant/sm83-test-data#8]
It appears the tests expect the carry bit to be set but according to the following docs the carry bit in register F is left unmodified.

https://rgbds.gbdev.io/docs/v0.7.0/gbz80.7#INC_r8
https://izik1.github.io/gbops/

Sample test:
```
{
    "name": "04 54 70",
    "initial": {
      "a": 228,
      "b": 166,
      "c": 255,
      "d": 3,
      "e": 101,
      "f": 176,
      "h": 95,
      "l": 64,
      "pc": 62887,
      "sp": 39500,
      "ram": [
        [
          62886,
          4
        ],
        [
          62887,
          84
        ],
        [
          62888,
          112
        ]
      ]
    },
    "final": {
      "a": 228,
      "b": 167,
      "c": 255,
      "d": 3,
      "e": 101,
      "f": 16,
      "h": 95,
      "l": 64,
      "pc": 62888,
      "sp": 39500,
      "ram": [
        [
          62886,
          4
        ],
        [
          62887,
          84
        ],
        [
          62888,
          112
        ]
      ]
    }
```

**Comment by adtennant** [comment]
In your example the `f` register is `0b10110000`, i.e. the `Z`, `H` and `C` flags are set going into the test. After the test it is `0b00010000`, i.e. only the `C` is set.

As per the linked docs `INC r8` should modify `Z` and `H`, clear `N` and leave `C` intact.

**Comment by Hucaru** [comment]
Ah, thanks!
